version: '3.8'

services:
  detooz-backend:
    container_name: detooz_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      # Persist SQLite Database
      - ./backend/detooz.db:/app/detooz.db
      # Persist Logs
      - ./backend/logs:/app/logs
      # Mount service account if needed (though it might be copied in build if not .dockerignored)
      - ./backend/firebase-service-account.json:/app/firebase-service-account.json
    env_file:
      - ./backend/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
